In [1]:
from datasets import load_dataset, DatasetDict
import pandas as pd 
import os

data_dir = "./data/processed_data/scaffold/"
# Load the datasets

train_dataset = pd.read_csv(os.path.join(data_dir, "train/metadata.csv"))

In [2]:
train_dataset

Unnamed: 0                                             smiles  \
0              0  CC(=O)N(CC(O)CN(C(C)=O)C1:C(I):C(C(=O)NCC(O)CO...   
1              1  O=C1CN(N=CC2:C:C:C(C3:C:C:C([N+](=O)[O-]):C:C:...   
2              2           CC12CCC3C(CCC4=CC(=O)C=CC43C)C1CCC(=O)O2   
3              3  O=C1C(=O)C2:C:C:C:C:C:2C(O)=C1C1CCC(C2:C:C:C(C...   
4              4                 O=C(NCCN1CCOCC1)C1:C:C:C(Cl):C:C:1   
...          ...                                                ...   
1138        1138            CC(C)NCC(O)COC1:C:C:C:C2:[NH]:C:C:C:1:2   
1139        1139    CNS(=O)(=O)CC1:C:C:C2:[NH]:C:C(CCN(C)C):C:2:C:1   
1140        1140  CC(C)C[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)O...   
1141        1141                        CCC1C(=O)OCC1CC1:C:N:C:N:1C   
1142        1142                     O=C1:N:C:N:C2:[NH]:[NH]:C:C:12   

      Hepatobiliary disorders  Metabolism and nutrition disorders  \
0                           0                                   1   
1                           1                                   1   
2                           0                                   1   
3                           1                                   1   
4                           0                                   1   
...                       ...                                 ...   
1138                        0                                   0   
1139                        0                                   1   
1140                        0                                   1   
1141                        1                                   1   
1142                        1                                   1   

      Product issues  Eye disorders  Investigations  \
0                  0              1               1   
1                  0              1               1   
2                  0              0               1   
3                  0              1               1   
4                  0              1               1   
...              ...            ...             ...   
1138               0              1               1   
1139               0              1               1   
1140               0              1               1   
1141               0              1               1   
1142               0              1               1   

      Musculoskeletal and connective tissue disorders  \
0                                                   1   
1                                                   1   
2                                                   0   
3                                                   1   
4                                                   1   
...                                               ...   
1138                                                1   
1139                                                1   
1140                                                1   
1141                                                1   
1142                                                1   

      Gastrointestinal disorders  Social circumstances  ...  \
0                              1                     0  ...   
1                              1                     0  ...   
2                              1                     0  ...   
3                              1                     0  ...   
4                              1                     0  ...   
...                          ...                   ...  ...   
1138                           1                     0  ...   
1139                           1                     1  ...   
1140                           1                     1  ...   
1141                           1                     1  ...   
1142                           1                     0  ...   

      Congenital, familial and genetic disorders  Infections and infestations  \
0                                              0                            1   
1                                              0           

In [3]:
train_dataset.drop(0)

Unnamed: 0                                             smiles  \
1              1  O=C1CN(N=CC2:C:C:C(C3:C:C:C([N+](=O)[O-]):C:C:...   
2              2           CC12CCC3C(CCC4=CC(=O)C=CC43C)C1CCC(=O)O2   
3              3  O=C1C(=O)C2:C:C:C:C:C:2C(O)=C1C1CCC(C2:C:C:C(C...   
4              4                 O=C(NCCN1CCOCC1)C1:C:C:C(Cl):C:C:1   
5              5                               OCC1OC(O)C(O)C(O)C1O   
...          ...                                                ...   
1138        1138            CC(C)NCC(O)COC1:C:C:C:C2:[NH]:C:C:C:1:2   
1139        1139    CNS(=O)(=O)CC1:C:C:C2:[NH]:C:C(CCN(C)C):C:2:C:1   
1140        1140  CC(C)C[C@H](NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)O...   
1141        1141                        CCC1C(=O)OCC1CC1:C:N:C:N:1C   
1142        1142                     O=C1:N:C:N:C2:[NH]:[NH]:C:C:12   

      Hepatobiliary disorders  Metabolism and nutrition disorders  \
1                           1                                   1   
2                           0                                   1   
3                           1                                   1   
4                           0                                   1   
5                           0                                   1   
...                       ...                                 ...   
1138                        0                                   0   
1139                        0                                   1   
1140                        0                                   1   
1141                        1                                   1   
1142                        1                                   1   

      Product issues  Eye disorders  Investigations  \
1                  0              1               1   
2                  0              0               1   
3                  0              1               1   
4                  0              1               1   
5                  0              1               1   
...              ...            ...             ...   
1138               0              1               1   
1139               0              1               1   
1140               0              1               1   
1141               0              1               1   
1142               0              1               1   

      Musculoskeletal and connective tissue disorders  \
1                                                   1   
2                                                   0   
3                                                   1   
4                                                   1   
5                                                   0   
...                                               ...   
1138                                                1   
1139                                                1   
1140                                                1   
1141                                                1   
1142                                                1   

      Gastrointestinal disorders  Social circumstances  ...  \
1                              1                     0  ...   
2                              1                     0  ...   
3                              1                     0  ...   
4                              1                     0  ...   
5                              1                     0  ...   
...                          ...                   ...  ...   
1138                           1                     0  ...   
1139                           1                     1  ...   
1140                           1                     1  ...   
1141                           1                     1  ...   
1142                           1                     0  ...   

      Congenital, familial and genetic disorders  Infections and infestations  \
1                                              0                            0   
2                                              0           

In [4]:
train_dataset.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
class_names = train_dataset.columns
print(class_names)
print("num_labels:", len(class_names))
print(class_names[0])

Index(['smiles', 'Hepatobiliary disorders',
       'Metabolism and nutrition disorders', 'Product issues', 'Eye disorders',
       'Investigations', 'Musculoskeletal and connective tissue disorders',
       'Gastrointestinal disorders', 'Social circumstances',
       'Immune system disorders', 'Reproductive system and breast disorders',
       'Neoplasms benign, malignant and unspecified (incl cysts and polyps)',
       'General disorders and administration site conditions',
       'Endocrine disorders', 'Surgical and medical procedures',
       'Vascular disorders', 'Blood and lymphatic system disorders',
       'Skin and subcutaneous tissue disorders',
       'Congenital, familial and genetic disorders',
       'Infections and infestations',
       'Respiratory, thoracic and mediastinal disorders',
       'Psychiatric disorders', 'Renal and urinary disorders',
       'Pregnancy, puerperium and perinatal conditions',
       'Ear and labyrinth disorders', 'Cardiac disorders',
       'N

In [6]:
class_distributions = []

for class_name in class_names[1:]:
    class_distribution = train_dataset[class_name].value_counts()
    class_distributions.append(class_distribution)
print(class_distributions)

[1    573
0    570
Name: Hepatobiliary disorders, dtype: int64, 1    787
0    356
Name: Metabolism and nutrition disorders, dtype: int64, 0    1124
1      19
Name: Product issues, dtype: int64, 1    696
0    447
Name: Eye disorders, dtype: int64, 1    914
0    229
Name: Investigations, dtype: int64, 1    788
0    355
Name: Musculoskeletal and connective tissue disorders, dtype: int64, 1    1025
0     118
Name: Gastrointestinal disorders, dtype: int64, 0    954
1    189
Name: Social circumstances, dtype: int64, 1    813
0    330
Name: Immune system disorders, dtype: int64, 0    576
1    567
Name: Reproductive system and breast disorders, dtype: int64, 0    848
1    295
Name: Neoplasms benign, malignant and unspecified (incl cysts and polyps), dtype: int64, 1    1030
0     113
Name: General disorders and administration site conditions, dtype: int64, 0    898
1    245
Name: Endocrine disorders, dtype: int64, 0    976
1    167
Name: Surgical and medical procedures, dtype: int64, 1    877
0

In [7]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Replace 'path_to_your_project/ChemBERTa/checkpoint-360' with the actual path
model_path = './ChemBERTa/checkpoint-360'
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

/home/ito/anaconda3/envs/project/lib/python3.11/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [8]:
test_dataset = pd.read_csv(os.path.join(data_dir, "test/metadata.csv"))
test_smiles = test_dataset["smiles"].values
test_ground_truth = test_dataset.drop(["smiles", "Unnamed: 0"], axis=1)

In [9]:
test_ground_truth

Hepatobiliary disorders  Metabolism and nutrition disorders  \
0                          1                                   1   
1                          1                                   1   
2                          1                                   1   
3                          1                                   1   
4                          1                                   1   
..                       ...                                 ...   
137                        1                                   1   
138                        0                                   1   
139                        1                                   1   
140                        1                                   1   
141                        1                                   1   

     Product issues  Eye disorders  Investigations  \
0                 0              1               1   
1                 0              1               1   
2                 0              1               1   
3                 0              1               1   
4                 0              1               1   
..              ...            ...             ...   
137               0              0               1   
138               0              0               1   
139               0              1               1   
140               0              1               1   
141               0              1               1   

     Musculoskeletal and connective tissue disorders  \
0                                                  1   
1                                                  1   
2                                                  1   
3                                                  1   
4                                                  1   
..                                               ...   
137                                                1   
138                                                1   
139                                                1   
140                                                1   
141                                                1   

     Gastrointestinal disorders  Social circumstances  \
0                             1                     0   
1                             1                     1   
2                             1                     1   
3                             1                     0   
4                             1                     1   
..                          ...                   ...   
137                           1                     0   
138                           1                     0   
139                           1                     1   
140                           1                     0   
141                           1                     0   

     Immune system disorders  Reproductive system and breast disorders  ...  \
0                          1                                         1  ...   
1                          1                                         1  ...   
2                          1                                         1  ...   
3                          1                                         1  ...   
4                          1                                         1  ...   
..                       ...                                       ...  ...   
137                        0                                         1  ...   
138                        0                                         0  ...   
139                        1                                         1  ...   
140                        1                                         0  ...   
141                        1                                         1  ...   

     Congenital, familial and genetic disorders  Infections and infestations  \
0                                             0                            1   
1                                             0                         

In [10]:
test_ground_truth_values = test_ground_truth.values

In [11]:
test_ground_truth_values

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1]])

In [12]:
test_smiles.shape
test_smiles_list = test_smiles.tolist()

In [13]:
tokenized_inputs = tokenizer(test_smiles_list, padding="max_length", truncation=True, max_length=300, return_tensors="pt")

In [39]:
import torch

# Assuming you are using a PyTorch model
with torch.no_grad():
    outputs = model(**tokenized_inputs)

In [40]:
outputs["logits"][0]

tensor([ 0.1015,  0.7590, -3.3706,  0.6905,  1.4342,  1.0004,  2.1501, -1.4398,
         1.0378,  0.0652, -1.0571,  2.4634, -1.3108, -1.8690,  1.2413,  0.1871,
         2.7723, -1.4554,  0.8102,  1.1380,  1.0592,  0.6617, -2.6285,  0.1491,
         0.7149,  2.4094,  0.7145])

In [41]:
probabilities = torch.sigmoid(outputs.logits)
probabilities[0]

tensor([0.5254, 0.6811, 0.0332, 0.6661, 0.8076, 0.7311, 0.8957, 0.1916, 0.7384,
        0.5163, 0.2579, 0.9215, 0.2124, 0.1337, 0.7758, 0.5466, 0.9412, 0.1892,
        0.6922, 0.7573, 0.7425, 0.6597, 0.0673, 0.5372, 0.6715, 0.9175, 0.6714])

In [42]:
thredshold = 0.5
predictions = (probabilities > thredshold).int()
predictions[0]

tensor([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 1, 1], dtype=torch.int32)

In [55]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

import numpy as np

# Convert your tensors to numpy arrays if they aren't already
predictions_np = predictions.numpy()
true_labels_np = test_ground_truth_values  # Replace true_labels with your actual labels
probabilities_np = probabilities.numpy()

# Initialize lists to store metrics for each label
accuracies = []
precisions = []
recalls = []
f1_scores = []
AUC_scores = []

# Calculate metrics for each label
for label in range(predictions_np.shape[1]):
    print(label)
    accuracies.append(accuracy_score(true_labels_np[:, label], predictions_np[:, label]))
    precisions.append(precision_score(true_labels_np[:, label], predictions_np[:, label], zero_division=0))
    recalls.append(recall_score(true_labels_np[:, label], predictions_np[:, label], zero_division=0))
    f1_scores.append(f1_score(true_labels_np[:, label], predictions_np[:, label], zero_division=0))
    if (true_labels_np[:, label].sum() != 0):
        AUC_scores.append(roc_auc_score(true_labels_np[:, label], probabilities_np[:, label]))

# Calculate average of each metric
average_accuracy = np.mean(accuracies)
average_precision = np.mean(precisions)
average_recall = np.mean(recalls)
average_f1_score = np.mean(f1_scores)
average_AUC = np.mean(AUC_scores)

print(f"Average Accuracy: {average_accuracy}")
print(f"Average Precision: {average_precision}")
print(f"Average Recall: {average_recall}")
print(f"Average F1 Score: {average_f1_score}")
print(f"Average AUC: {average_AUC}")

0
2309
1
2309
2
2309
3
2309
4
2309
5
2309
6
2309
7
2309
8
2309
9
2309
10
2309
11
2309
12
2309
13
2309
14
2309
15
2309
16
2309
17
2309
18
2309
19
2309
20
2309
21
2309
22
2309
23
2309
24
2309
25
2309
26
2309
Average Accuracy: 0.7743870631194576
Average Precision: 0.6030046273461471
Average Recall: 0.7033717827127414
Average F1 Score: 0.623087264779289
Average AUC: 0.6105134605096828


In [1]:
print(f1_scores)

NameError: name 'f1_scores' is not defined

In [53]:
true_labels_np[:, 2].sum()
# probabilities_np[:,2]
# roc_auc_score(true_labels_np[:, 2], probabilities_np[:,2])

0

In [19]:
poor_shredshold = 0.7
index_with_poor_score = [index for index, value in enumerate(accuracies) if value < poor_shredshold]
print(index_with_poor_score)


[0, 1, 3, 9, 21, 23]


In [20]:
id2label = {idx:label for idx, label in enumerate(class_names[1:])}
label2id = {label:idx for idx, label in enumerate(class_names[1:])}
print(id2label)
print(label2id)

{0: 'Hepatobiliary disorders', 1: 'Metabolism and nutrition disorders', 2: 'Product issues', 3: 'Eye disorders', 4: 'Investigations', 5: 'Musculoskeletal and connective tissue disorders', 6: 'Gastrointestinal disorders', 7: 'Social circumstances', 8: 'Immune system disorders', 9: 'Reproductive system and breast disorders', 10: 'Neoplasms benign, malignant and unspecified (incl cysts and polyps)', 11: 'General disorders and administration site conditions', 12: 'Endocrine disorders', 13: 'Surgical and medical procedures', 14: 'Vascular disorders', 15: 'Blood and lymphatic system disorders', 16: 'Skin and subcutaneous tissue disorders', 17: 'Congenital, familial and genetic disorders', 18: 'Infections and infestations', 19: 'Respiratory, thoracic and mediastinal disorders', 20: 'Psychiatric disorders', 21: 'Renal and urinary disorders', 22: 'Pregnancy, puerperium and perinatal conditions', 23: 'Ear and labyrinth disorders', 24: 'Cardiac disorders', 25: 'Nervous system disorders', 26: 'Inj

In [21]:
label_with_poor_score = [id2label[idx] for idx in index_with_poor_score]
print(label_with_poor_score)

['Hepatobiliary disorders', 'Metabolism and nutrition disorders', 'Eye disorders', 'Reproductive system and breast disorders', 'Renal and urinary disorders', 'Ear and labyrinth disorders']


In [22]:
class_distributions_with_poor_score =  [class_distributions[idx] for idx in index_with_poor_score]
for data in class_distributions_with_poor_score:
    print(data)

1    573
0    570
Name: Hepatobiliary disorders, dtype: int64
1    787
0    356
Name: Metabolism and nutrition disorders, dtype: int64
1    696
0    447
Name: Eye disorders, dtype: int64
0    576
1    567
Name: Reproductive system and breast disorders, dtype: int64
1    710
0    433
Name: Renal and urinary disorders, dtype: int64
0    636
1    507
Name: Ear and labyrinth disorders, dtype: int64


In [23]:
class_distributions_with_poor_score[1]

1    787
0    356
Name: Metabolism and nutrition disorders, dtype: int64

In [24]:
print(f1_scores)


[0.7024390243902439, 0.8166666666666667, 0.0, 0.7555555555555554, 0.916030534351145, 0.859437751004016, 0.982078853046595, 0.0, 0.873015873015873, 0.7103825136612022, 0.0, 0.9710144927536231, 0.052631578947368425, 0.0, 0.8774703557312252, 0.8220338983050849, 0.982078853046595, 0.0, 0.8264462809917354, 0.8455284552845529, 0.880952380952381, 0.8215767634854771, 0.0, 0.4827586206896552, 0.825, 0.9747292418772564, 0.8455284552845529]


In [25]:
def extract_poor_predictoin_index(metrics, thredshold):
    poor_predictoin_index = []
    for i, metric in enumerate(metrics):
        if metric < thredshold:
            poor_predictoin_index.append(i)
    return poor_predictoin_index

In [28]:
poor_index_f1 = extract_poor_predictoin_index(f1_scores, 0.5)
print(poor_index_f1)

[2, 7, 10, 12, 13, 17, 22, 23]


In [30]:
poor_labels_f1 = [id2label[idx] for idx in poor_index_f1]
print(poor_labels_f1)

['Product issues', 'Social circumstances', 'Neoplasms benign, malignant and unspecified (incl cysts and polyps)', 'Endocrine disorders', 'Surgical and medical procedures', 'Congenital, familial and genetic disorders', 'Pregnancy, puerperium and perinatal conditions', 'Ear and labyrinth disorders']


In [31]:
poor_distributions_f1 = [class_distributions[idx] for idx in poor_index_f1]
print(poor_distributions_f1)

[0    1124
1      19
Name: Product issues, dtype: int64, 0    954
1    189
Name: Social circumstances, dtype: int64, 0    848
1    295
Name: Neoplasms benign, malignant and unspecified (incl cysts and polyps), dtype: int64, 0    898
1    245
Name: Endocrine disorders, dtype: int64, 0    976
1    167
Name: Surgical and medical procedures, dtype: int64, 0    934
1    209
Name: Congenital, familial and genetic disorders, dtype: int64, 0    1046
1      97
Name: Pregnancy, puerperium and perinatal conditions, dtype: int64, 0    636
1    507
Name: Ear and labyrinth disorders, dtype: int64]


In [60]:
true_labels_np

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1]])

In [61]:
for label in range(predictions_np.shape[1]):
    print(true_labels_np[:, label])
    num_1 = true_labels_np[:, label].sum()
    num_0 = true_labels_np[:, label].shape[0] - num_1
    print("num_0:", num_0)
    print("num_1:", num_1)

[1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 0
 1 0 0 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 1
 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1
 0 0 1 1 1 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
num_0: 52
num_1: 90
[1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1
 1 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1
 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1]
num_0: 43
num_1: 99
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
num_0: 142
num_1: 0
[1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 1 